<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.splunk.test.PostMovies" tests="1" time="1.769" ignored="0" failures="1" timestamp="16 Jul 2018 03:38:50 GMT" skipped="0" hostname="Jagadeeshs-MacBook-Pro.local" errors="0">
  <testcase name="verifyPostingMovie" time="1.769" classname="com.splunk.test.PostMovies">
    <failure type="java.lang.AssertionError" message="Exception occured while getting resposne Hence Failing200">
      <![CDATA[java.lang.AssertionError: Exception occured while getting resposne Hence Failing200
	at org.testng.Assert.fail(Assert.java:94)
	at com.splunk.commons.ReusableFunctions.postMovie(ReusableFunctions.java:117)
	at com.splunk.test.PostMovies.verifyPostingMovie(PostMovies.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- verifyPostingMovie -->
</testsuite> <!-- com.splunk.test.PostMovies -->
